name: ğŸ’…ğŸ¼ PHP Linting (Pint)
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'
jobs:
  Pint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3

      - name: â¬‡ï¸ Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: ğŸ•µï¸ Launch Pint inspection
        run: vendor/bin/pint

      - name: ğŸ’¾ Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ğŸ’…ğŸ¼ PHP Linting (Pint)
          skip_fetch: true